// Code generated by "stringer -type=Condition"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InMessage-1]
	_ = x[InMask-2]
}

const _Condition_name = "InMessageInMask"

var _Condition_index = [...]uint8{0, 9, 15}

func (i MsgCondition) String() string {
	i -= 1
	if i >= MsgCondition(len(_Condition_index)-1) {
		return "Condition(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Condition_name[_Condition_index[i]:_Condition_index[i+1]]
}
