// Code generated by "stringer -type=Condition"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[InMessage-0]
	_ = x[InMask-2]
}

const (
	_Condition_name_0 = "InMessage"
	_Condition_name_1 = "InMask"
)

func (i Condition) String() string {
	switch {
	case i == 0:
		return _Condition_name_0
	case i == 2:
		return _Condition_name_1
	default:
		return "Condition(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
