// Code generated by "stringer -type=TraitType"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Unspecified-0]
	_ = x[NoTraits-1]
	_ = x[NotZero-2]
	_ = x[NotEqual-3]
	_ = x[Custom-4]
}

const _TraitType_name = "UnspecifiedNoTraitsNotZeroNotEqualCustom"

var _TraitType_index = [...]uint8{0, 11, 19, 26, 34, 40}

func (i TraitType) String() string {
	if i >= TraitType(len(_TraitType_index)-1) {
		return "TraitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TraitType_name[_TraitType_index[i]:_TraitType_index[i+1]]
}
