// Code generated by "stringer -type=trait"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[notZero-0]
	_ = x[calculated-1]
}

const _trait_name = "notZerocalculated"

var _trait_index = [...]uint8{0, 7, 17}

func (i trait) String() string {
	if i >= trait(len(_trait_index)-1) {
		return "trait(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _trait_name[_trait_index[i]:_trait_index[i+1]]
}
