// Code generated by "stringer -type=traitType"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[notZero-0]
	_ = x[calculated-1]
}

const _traitType_name = "notZerocalculated"

var _traitType_index = [...]uint8{0, 7, 17}

func (i traitType) String() string {
	if i >= traitType(len(_traitType_index)-1) {
		return "traitType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _traitType_name[_traitType_index[i]:_traitType_index[i+1]]
}
