// Code generated by "stringer -type=UhOhType"; DO NOT EDIT.

package propl

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NA-1]
	_ = x[Field-2]
	_ = x[Request-4]
}

const (
	_UhOhType_name_0 = "NAField"
	_UhOhType_name_1 = "Request"
)

var (
	_UhOhType_index_0 = [...]uint8{0, 2, 7}
)

func (i UhOhType) String() string {
	switch {
	case 1 <= i && i <= 2:
		i -= 1
		return _UhOhType_name_0[_UhOhType_index_0[i]:_UhOhType_index_0[i+1]]
	case i == 4:
		return _UhOhType_name_1
	default:
		return "UhOhType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
